Expose API to set non earth DEMs flag
gazebosim/gz-common pull request #353
Opened 2022-05-10 00:58 UTC by adityapande-1995

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

# 🎉 New feature

## Summary
This PR exposes the ``isNonEarthDEM`` member so that it can be set before the ``Load`` function, if required.

## Test it
I'm not sure how a test case could work for this particular PR.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

2022-05-10 07:47 UTC, ahcorde requested changes
test?

2022-05-10 07:47 UTC, ahcorde commented on geospatial/include/gz/common/geospatial/Dem.hh
> +      public: void SetNonEarthDEM(bool isNonEarthDem);
```suggestion
      public: void SetNonEarthDEM(bool _isNonEarthDem);
```

2022-05-10 07:47 UTC, ahcorde commented on geospatial/src/Dem.cc
> +void Dem::SetNonEarthDEM(bool isNonEarthDem)
```suggestion
void Dem::SetNonEarthDEM(bool _isNonEarthDem)
```

2022-05-13 19:18 UTC, adityapande-1995 commented on geospatial/include/gz/common/geospatial/Dem.hh
> +      public: void SetNonEarthDEM(bool isNonEarthDem);
Fixed

2022-05-13 19:18 UTC, adityapande-1995 commented on geospatial/src/Dem.cc
> +void Dem::SetNonEarthDEM(bool isNonEarthDem)
Fixed

2022-05-16 18:11 UTC, WilliamLewww approved these changes

2022-05-17 07:43 UTC, ahcorde requested changes

2022-05-17 07:43 UTC, ahcorde commented on geospatial/include/gz/common/geospatial/Dem.hh
> +      /// \param[in] isNonEarthDem Should be true if this is a
```suggestion
      /// \param[in] _isNonEarthDem Should be true if this is a
```

2022-05-17 12:41 UTC, mjcarroll commented
Was there a decision to revisit this variable naming?

2022-05-17 13:25 UTC, adityapande-1995 commented on geospatial/include/gz/common/geospatial/Dem.hh
> +      /// \param[in] isNonEarthDem Should be true if this is a
Resolved : https://github.com/gazebosim/gz-common/pull/353/commits/8bcc9d0ea068aa8992a9e0061ceedd43af7e95fd

2022-05-17 17:10 UTC, ahcorde approved these changes

2022-05-17 17:14 UTC, merged