Fix reading pixel values from single channel 16 bit image
gazebosim/gz-common pull request #439
Opened 2022-09-20 22:47 UTC by iche033

Signed-off-by: Ian Chen <ichen@osrfoundation.org>

# 🦟 Bug fix

## Summary

Currently the Image class calls `FreeImage_GetPixelIndex` to access pixel values of a single channel image. However, this function does not support reading values from 16 bit images. This PR fixes the issue by implement our own `PixelIndex`  function that includes logic for computing the pixel value of 16 bit image types.

Addition info: This is needed for loading 16 bit heightmaps. Currently it floods the console with `Image: Coordinates out of range` error msgs. This happens when the `Image::MaxColor` call is looping through the image pixels and calling `FreeImage_GetPixelIndex` function that fails on every iteration.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-09-21 11:20 UTC, ahcorde requested changes

2022-09-21 11:20 UTC, ahcorde commented on graphics/src/Image.cc
> +      /// \param[out] _color Pixel value at specified index
```suggestion
      /// \param[out] _color Pixel value at specified index
      /// \return
```

2022-09-21 21:42 UTC, nkoenig commented on graphics/src/Image.cc
> +      /// \param[out] _color Pixel value at specified index
[d1d0595](https://github.com/gazebosim/gz-common/pull/439/commits/d1d05950ca2b3a5c37448c11d0d994f264b2f2c1)

2022-09-21 21:51 UTC, nkoenig approved these changes

2022-09-22 06:30 UTC, ahcorde approved these changes

2022-09-22 07:08 UTC, merged