Build examples from CMake rather than executable
gazebosim/gz-common pull request #502
Opened 2023-04-11 23:19 UTC by mjcarroll

# 🦟 Bug fix

## Summary

Part of https://github.com/gazebosim/gz-cmake/pull/301

Test by building gz-common as normal and then running the "EXAMPLES_Configure_TEST" and "EXAMPLES_Build_TEST" via ctest.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2023-04-28 18:20 UTC, iche033 commented on examples/CMakeLists.txt
> +project(gz-math-examples)
`gz-common-examples`?

2023-05-09 07:47 UTC, ahcorde requested changes
`gz_build_examples` is not available. @mjcarroll do you need a `gz-cmake` release?

2023-05-22 12:45 UTC, mjcarroll commented
@osrf-jenkins retest this please

2023-05-31 13:30 UTC, mjcarroll commented
@osrf-jenkins retest this please

2023-07-17 08:25 UTC, ahcorde requested changes
macOS is faling

2023-07-17 21:13 UTC, mjcarroll commented
> macOS is faling

Addressed in https://github.com/gazebosim/gz-common/pull/524

2023-07-17 21:46 UTC, ahcorde approved these changes

2023-08-24 20:29 UTC, iche033 commented
macOS builds are failing to find gz-common5 when building examples. Is that expected?

2023-08-24 20:51 UTC, mjcarroll commented
> macOS builds are failing to find gz-common5 when building examples. Is that expected?

We either need to run `make install` before `make test` or skip the examples.  I would vote for the former as it exercises the examples.

2023-08-28 14:04 UTC, merged