Adds new function in MeshManager for performing convex decomposition
gazebosim/gz-common pull request #583
Opened 2024-03-13 01:42 UTC by iche033

# 🎉 New feature

## Summary

Adds function for doing convex decomposition using the header only library [V-HACD](https://github.com/kmammou/v-hacd).

The new function take a submesh and returns a vector of decomposed submeshes. Currently a couple of parameters are exposed:
* `_maxConvexHulls`: max number of convex hulls to produce
    * value: 16 (default in V-HACD: 64)
* `_voxelResolution`:  resolution of voxels to use when decomposing the submesh
    * value: 200000 (default in V-HACD: 400000)
   
These default values for these parameters are lower than the default values provided in V-HACD for a faster convex decomposition process as the process with original values could take quite some time for complex meshes.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-03-13 08:55 UTC, ahcorde requested changes

2024-03-13 08:55 UTC, ahcorde commented on graphics/src/MeshManager.cc
> +  std::vector<SubMesh> decomposed;
include `<vector>`

2024-03-13 08:55 UTC, ahcorde commented on graphics/src/MeshManager.cc
> +  uint32_t *indices = new uint32_t[indexCount];
include `<cstdint>`

2024-03-14 01:46 UTC, iche033 commented on graphics/src/MeshManager.cc
> +  std::vector<SubMesh> decomposed;
addressed in #585 that targets `main`

2024-03-14 01:46 UTC, iche033 commented on graphics/src/MeshManager.cc
> +  uint32_t *indices = new uint32_t[indexCount];
addressed in #585 that targets `main`

2024-03-14 01:47 UTC, iche033 commented
replaced by #585 - > `main`

2024-03-14 01:47 UTC, closed without merging