Prototype of using STB rather than FreeImage
gazebosim/gz-common pull request #590
Opened 2024-04-02 16:44 UTC by mjcarroll

2024-04-03 08:45 UTC, ahcorde requested changes

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoader.cc
> + * Copyright (C) 2023 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2024 Open Source Robotics Foundation
```

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoader.cc
> +  std::string fullName = _filename;
include `<string>`

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoader.cc
> +}  //  namespace gz::common
```suggestion
}
}  //  namespace gz::common
```

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoader.hh
> + * Copyright (C) 2023 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2024 Open Source Robotics Foundation
```

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoader.hh
> +  std::string filename {""};
include `<string>`

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoader.hh
> +  std::vector<uint8_t> data;
include `<vector>`, `<cstdint>`

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoader.hh
> +  public: std::shared_ptr<ImageData> Load(const std::string &_filename) const;
include `<memory>`

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoaderFreeImage.cc
> + * Copyright (C) 2023 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2024 Open Source Robotics Foundation
```

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoaderFreeImage.cc
> +  auto  width = FreeImage_GetWidth(_bitmap);
```suggestion
  auto width = FreeImage_GetWidth(_bitmap);
```

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoaderFreeImage.cc
> +      std::swap(pixel[0], pixel[2]);
include `<algorithm>`

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoaderFreeImage.cc
> +std::vector<unsigned char> DataImpl(FIBITMAP *_img)
include `<vector>`

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoaderFreeImage.cc
> +    FREE_IMAGE_FORMAT fifmt = FreeImage_GetFIFFromFilename(_filename.c_str());
indentation 2 spaces, like the other methods

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoaderFreeImage.hh
> + * Copyright (C) 2023 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2024 Open Source Robotics Foundation
```

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoaderFreeImage.hh
> +  protected: virtual std::shared_ptr<ImageData> LoadImpl(const std::string &_filename) const override;
include `<memory>`, `<string>`

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoaderSTB.cc
> + * Copyright (C) 2023 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2024 Open Source Robotics Foundation
```

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoaderSTB.cc
> +namespace gz::common
```suggestion
#include <gz/common/Console.hh>

namespace gz::common
```

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoaderSTB.cc
> +  stbi_set_unpremultiply_on_load( 1 );
```suggestion
  stbi_convert_iphone_png_to_rgb(1);
  stbi_set_unpremultiply_on_load(1);
```

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoaderSTB.cc
> +ImageLoaderSTB::LoadImpl_8bit(const std::string &_filename) const
include `<memory>`, `<string>`

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoaderSTB.cc
> +    const uint8_t* srcRow = &data[row_idx * ret->pitch];
include `<cstdint>`

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoaderSTB.cc
> +  /*
remove?

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoaderSTB.cc
> +  /*
remove?

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoaderSTB.cc
> +std::shared_ptr<ImageData>
```suggestion
}

std::shared_ptr<ImageData>
```

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoaderSTB.hh
> + * Copyright (C) 2023 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2024 Open Source Robotics Foundation
```

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoaderSTB.hh
> +  protected: virtual std::shared_ptr<ImageData> LoadImpl(const std::string &_filename) const override;
include `<string>`, `<memory>`

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoader_TEST.cc
> + * Copyright (C) 2016 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2024 Open Source Robotics Foundation
```

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoader_TEST.cc
> +const std::string kTestDataGazeboJpeg =  // NOLINT(*)
include `<string>`

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoader_TEST.cc
> +  auto loader = std::make_unique<TestImageLoader>();
include `<memory>`

2024-04-03 08:45 UTC, ahcorde commented on graphics/src/ImageLoader_TEST.cc
> +
```suggestion
```

2024-08-12 19:16 UTC, azeey commented
Per our discussion in the PMC meeting, this is unlikely to make it into Ionic, so I'll go ahead and remove the `beta` label.

2025-01-21 13:19 UTC, nim65s commented
Hello, 

What does this need ? Only applying the review ?
If so, should I give it a try ?

2025-01-21 15:44 UTC, mjcarroll commented
> What does this need ?

I don't remember the exact state I left this in, but it's going to need more than that, I believe.

The issue here is that Freeimage is actually part of the public API (unfortunately), so I was trying to remove that and keep tests passing. This was to get the conversation started, but didn't go all the way.

2025-07-17 19:35 UTC, closed without merging