5 :arrow_right: 4 - EnumIface: suppress deprecation warning (#540)
gazebosim/gz-common pull request #600
Opened 2024-04-25 14:44 UTC by Crola1702

# 🦟 Bug fix

Fixes #505 

## Summary
Backport of https://github.com/gazebosim/gz-common/pull/540

## Checklist
- [X] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-04-25 15:55 UTC, azeey requested changes

2024-04-25 15:55 UTC, azeey commented on include/gz/common/EnumIface.hh
> +    GZ_UTILS_WARN_IGNORE__DEPRECATED_DECLARATION
You'll need to include https://github.com/gazebosim/gz-utils/blob/ign-utils1/include/gz/utils/SuppressWarning.hh and use the `IGN` prefix. Unfortunately, these macros don't have a `GZ` prefixed alias in `ign-utils1`.

2024-04-29 18:13 UTC, scpeters commented
This change also required calling `target_link_library` on the utils library, which I've done in https://github.com/gazebosim/gz-common/commit/6652132af4f72217dfb30ac105d001a0a2be8b30 in a way that will minimize the diff when merging forward to `gz-common5`. Feel free to cherry-pick into this branch.

I think it is safe for our Ubuntu packages because the `libignition-common4-core-dev` already depends on `libignition-utils1-dev` (see [common4 control file](https://github.com/gazebo-release/gz-common4-release/blob/main/ubuntu/debian/control#L46))

2024-05-07 21:33 UTC, azeey requested changes

2024-05-07 21:33 UTC, azeey commented on src/CMakeLists.txt
> +    gz-utils${GZ_UTILS_VER}::gz-utils${GZ_UTILS_VER}
```suggestion
    ignition-utils${IGN_UTILS_VER }::ignition-utils${IGN_UTILS_VER }
```

2024-05-07 21:34 UTC, azeey commented
A version that doesn't use the ign-utils macros is in https://github.com/gazebosim/gz-common/pull/604. We can still merge this since the macros are better.

2024-05-08 14:23 UTC, Crola1702 commented
I think everything is ready to go. Waiting for approvals and then merge

2024-05-08 16:31 UTC, azeey commented
The examples are failing on CI. This also shows that we are changing the dependency on ign-utils from being a requirement of the graphics component to being a requirement for the core library. I'm not exactly sure why the example is failing, but I'm inclined to close this PR and live with the bare pragmas that were added in #603.

2024-05-10 16:29 UTC, closed without merging