Replace GTS with CDT
gazebosim/gz-common pull request #617
Opened 2024-07-24 19:15 UTC by mjcarroll

This removes the dependency on GTS.

* It removes the Mesh boolean operations functions, which were part of the building editor in Gazebo-classic but are unused in modern gazebo.
* It replaces the GTS delaunay triangulation with the header-only CDT library.

2024-07-29 22:07 UTC, scpeters reviewed
some small whitespace nits

and I've prepared a change for homebrew-simulation for after this lands: https://github.com/osrf/homebrew-simulation/pull/2704

2024-08-05 22:08 UTC, azeey reviewed
The MeshCSG code was used in Gazebo-classic to implement the Building Editor. Since there is no plan to port this to modern Gazebo (we can potentially use [rmf_site](https://github.com/open-rmf/rmf_site) for this in the future), I'd say let's go ahead and remove it from gz-common.

2024-08-12 23:26 UTC, iche033 commented
gts dep removal in the gz-common6-release repo when this lands: https://github.com/gazebo-release/gz-common6-release/pull/4

2024-08-14 00:55 UTC, iche033 commented
I tested this with the polylines.sdf world and I think some of the triangles may be oriented incorrectly, i.e. normals are in the opposite direction:

left: GTS vs right: CDT

![cdt_tri](https://github.com/user-attachments/assets/fff3183b-f2cc-4e83-a7c6-f58d7305c2c1)

2024-08-15 18:39 UTC, scpeters commented on graphics/src/CDT/CDT.h
👍

2024-08-15 18:40 UTC, scpeters commented on graphics/include/gz/common/MeshManager.hh
> -          const gz::math::Pose3d &_offset = gz::math::Pose3d::Zero);
* [ ] update the migration guide to note the dependency change and the removal of this API

2024-08-15 20:00 UTC, scpeters commented
> I tested this with the polylines.sdf world and I think some of the triangles may be oriented incorrectly, i.e. normals are in the opposite direction:

I added a printout to the DelaunayTriangulation test to show the vertices for the triangles:

## patch

<details>

~~~
diff --git a/graphics/src/DelaunayTriangulation_TEST.cc b/graphics/src/DelaunayTriangulation_TEST.cc
index df919d3..c441257 100644
--- a/graphics/src/DelaunayTriangulation_TEST.cc
+++ b/graphics/src/DelaunayTriangulation_TEST.cc
@@ -69,6 +69,32 @@ TEST_F(DelaunayTriangulation, DelaunayTriangulation)
   // same as number of vertices in the path
   EXPECT_EQ(subMesh.VertexCount(), 8u);
 
+  std::cerr << subMesh.Max() << '\n';
+  std::cerr << subMesh.Min() << '\n';
+  // Print vertices
+  std::cerr << "vertices: \n";
+  for (int v = 0; v < subMesh.VertexCount(); ++v)
+  {
+    std::cerr << subMesh.Vertex(v) << '\n';
+  }
+  // Print normals
+  std::cerr << "normals: \n";
+  for (int v = 0; v < subMesh.NormalCount(); ++v)
+  {
+    std::cerr << subMesh.Normal(v) << '\n';
+  }
+
   // there should be 8 triangles.
   EXPECT_EQ(subMesh.IndexCount() / 3u, 8u);
+  // Print triangles
+  std::cerr << "triangles: \n";
+  for (int i = 0; i < subMesh.IndexCount() / 3u; ++i)
+  {
+    int i1 = subMesh.Index(i*3 + 0);
+    int i2 = subMesh.Index(i*3 + 1);
+    int i3 = subMesh.Index(i*3 + 2);
+    std::cerr << '[' << subMesh.Vertex(i1) << "]\n"
+              << '[' << subMesh.Vertex(i2) << "]\n"
+              << '[' << subMesh.Vertex(i3) << "]\n\n";
+  }
 }
~~~

</details>

## output with GTS

<details>

~~~
[ RUN      ] GTSMeshUtils.DelaunayTriangulation
1 1 0
0 0 0
vertices: 
0.75 0.75 0
1 0 0
1 1 0
0.75 0.25 0
0.25 0.75 0
0 1 0
0.25 0.25 0
0 0 0
normals: 
triangles: 
[0.75 0.75 0]
[1 1 0]
[1 0 0]

[0.75 0.25 0]
[0.75 0.75 0]
[1 0 0]

[0.25 0.75 0]
[0.25 0.25 0]
[0 1 0]

[0.75 0.25 0]
[1 0 0]
[0.25 0.25 0]

[1 0 0]
[0 0 0]
[0.25 0.25 0]

[0.25 0.25 0]
[0 0 0]
[0 1 0]

[0.75 0.75 0]
[0.25 0.75 0]
[1 1 0]

[0.25 0.75 0]
[0 1 0]
[1 1 0]

[       OK ] GTSMeshUtils.DelaunayTriangulation (1 ms)
~~~

</details>

## output with CDT

<details>

~~~
[ RUN      ] DelaunayTriangulation.DelaunayTriangulation
1 1 0
0 0 0
vertices: 
0 0 0
1 0 0
1 1 0
0 1 0
0.25 0.25 0
0.25 0.75 0
0.75 0.75 0
0.75 0.25 0
normals: 
triangles: 
[0.75 0.75 0]
[1 1 0]
[0 1 0]

[0.25 0.75 0]
[0.75 0.75 0]
[0 1 0]

[0.25 0.25 0]
[0 1 0]
[0 0 0]

[0.75 0.25 0]
[0.25 0.25 0]
[1 0 0]

[0.25 0.75 0]
[0 1 0]
[0.25 0.25 0]

[0.75 0.25 0]
[1 0 0]
[0.75 0.75 0]

[1 0 0]
[1 1 0]
[0.75 0.75 0]

[1 0 0]
[0.25 0.25 0]
[0 0 0]

[       OK ] DelaunayTriangulation.DelaunayTriangulation (1 ms)
~~~

</details>

2024-08-15 20:09 UTC, iche033 commented
> > I tested this with the polylines.sdf world and I think some of the triangles may be oriented incorrectly, i.e. normals are in the opposite direction:
> 
> I added a printout to the DelaunayTriangulation test to show the vertices for the triangles:
> 
> ## patch
> ## output with GTS
> ## output with CDT

Thanks, I created a fix for this in #623. It also addresses other feedback in this PR.

2024-08-15 23:02 UTC, scpeters commented on graphics/src/DelaunayTriangulation_TEST.cc
> +  for (int t = 0; t < subMesh.IndexCount() / 3u; ++t)
```suggestion
  for (unsigned int t = 0; t < subMesh.IndexCount() / 3u; ++t)
```
apologies I missed the compiler warning in #624

2024-08-15 23:03 UTC, scpeters commented
I think we could ignore `graphics/src/CDT` in [codecov.yml](https://github.com/gazebosim/gz-common/blob/mjcarroll/cdt/codecov.yml)

2024-08-16 00:12 UTC, iche033 commented
> I think we could ignore `graphics/src/CDT` in [codecov.yml](https://github.com/gazebosim/gz-common/blob/mjcarroll/cdt/codecov.yml)

I updated the ignore files in [7ddc32a](https://github.com/gazebosim/gz-common/pull/617/commits/7ddc32acca654f93fd9c17c12b7124c491459105)

2024-08-16 17:23 UTC, scpeters approved these changes

2024-08-16 17:25 UTC, scpeters requested changes
forgot one thing: we can remove the following line

https://github.com/gazebosim/gz-common/blob/mjcarroll/cdt/.github/ci/packages.apt#L8

2024-08-16 17:26 UTC, scpeters approved these changes

2024-08-16 20:16 UTC, iche033 approved these changes

2024-08-16 20:17 UTC, iche033 commented
removed gts dep from package.xml in a159b79

2024-08-16 21:26 UTC, merged