Fix gltf lightmap
gazebosim/gz-common pull request #630
Opened 2024-08-30 00:47 UTC by iche033

# 🦟 Bug fix

## Summary

Fix loading gltf / glb mesh files with lightmaps. Currently the lightmap is ignored if there's a combined roughness + metalness texture. This PR fixes the problem by loading the lightmap (ambient occlusion data) from the roughness + metalness texture.

Tested with a few [gltf sample models](https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0) (water bottle, barramundi fish, damaged helmet)

Here are screenshots of the [BarramundiFish](https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0/BarramundiFish) before (left) and after (right) the change. I removed the albedo map to better visualize the effect of the lightmap:

<img width="251" alt="barramundi_no_lightmap" src="https://github.com/user-attachments/assets/ba0262d2-30f0-493d-b160-ba51eef35c8d">

<img width="244" alt="barramundi_lightmap" src="https://github.com/user-attachments/assets/44f530ae-7cf3-4e7b-8aa8-7c9d3e58c0ad">

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-08-30 06:41 UTC, ahcorde requested changes
just some nits, otherwise LGTM

2024-08-30 06:41 UTC, ahcorde commented on graphics/src/AssimpLoader.cc
> +      std::vector<unsigned char> texRData(origRGBAData.size());
include `<vector>`

2024-08-30 06:41 UTC, ahcorde commented on graphics/src/AssimpLoader.cc
> +      auto tex = std::make_shared<Image>();
include `<memory>`

2024-09-05 17:57 UTC, iche033 commented on graphics/src/AssimpLoader.cc
> +      auto tex = std::make_shared<Image>();
[29b17f1](https://github.com/gazebosim/gz-common/pull/630/commits/29b17f164e5bc7da886db0c00bc44d04f10baa21)

2024-09-05 17:57 UTC, iche033 commented on graphics/src/AssimpLoader.cc
> +      std::vector<unsigned char> texRData(origRGBAData.size());
[29b17f1](https://github.com/gazebosim/gz-common/pull/630/commits/29b17f164e5bc7da886db0c00bc44d04f10baa21)

2024-09-05 19:01 UTC, iche033 commented
Some tests in UNIT_AssimpLoader_TEST on hombrew are failing. I noticed that failing in main as well and could be due to a new AssimpLoader homebrew bottle. I ticketed an issue for it: https://github.com/gazebosim/gz-common/issues/633

2024-09-05 20:31 UTC, ahcorde approved these changes

2024-09-05 21:33 UTC, iche033 commented
Fixed homebrew CI in https://github.com/gazebosim/gz-common/pull/634

2024-09-05 22:30 UTC, merged